# Generated by Django 3.2.12 on 2022-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.CharField(max_length=300),
        ),
    ]
