# Generated by Django 5.0.3 on 2024-03-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devProfiles', '0004_users_photo'),
    ]

    operations = [
    ]
