# Generated by Django 5.0.3 on 2024-03-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devProfiles', '0005_dell_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.CharField(max_length=300),
        ),
    ]
