# Generated by Django 4.1.13 on 2024-03-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devProfiles', '0006_alter_users_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
